version: '3'
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${VITE_SITE_CONTACT?Variable not set}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  redis-server:
    image: redis
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    ports:
      - 5000
    environment:
      - VITE_SITE_TITLE
      - VITE_SITE_HOST
      - VITE_SITE_CONTACT
      - REDIS_PREFIX
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.http.routers.node-server.rule=Host(`${VITE_SITE_HOST?Variable not set}`)"
      - "traefik.http.routers.node-server.entrypoints=websecure"
      - "traefik.http.routers.node-server.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
