version: '3'
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=hmj@goatpage.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  redis-server:
    image: redis
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    ports:
      - 5000
    environment:
      - VITE_SITE_TITLE
      - VITE_SITE_HOST
      - VITE_SITE_CONTACT
      - REDIS_PREFIX
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.http.routers.app.rule=Host(`slufe.net`,`www.slufe.net`,`slufe.fr`,`www.slufe.fr`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.routers.app.tls.domains[0].main=slufe.net"
      - "traefik.http.routers.app.tls.domains[0].sans=www.slufe.net"
      - "traefik.http.routers.app.tls.domains[1].main=slufe.fr"
      - "traefik.http.routers.app.tls.domains[1].sans=www.slufe.fr"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
