api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:

  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

http:
  routers:
    routerapi:
      entrypoints : ['api']
      service: "api@internal"
    router0:
      rule: "Host('hmdev.mshome.net')"
      entrypoints : ['websecure']
      service: slufe
  services:
    slufe:
      loadbalancer:
        servers:
          - url: 'http://localhost:5000'
