http:
  routers:
    router0:
      rule: Host(`hmdev.mshome.net`)
      entrypoints : 
        - websecure
      service: app
      tls: {}
  services:
    app:
      loadbalancer:
        servers:
          - url: 'http://172.18.0.1:5000'